fragment SiteSettingsParts on SiteSettings {
  __typename
  template {
    __typename
    type
    features {
      __typename
      shop {
        __typename
        enabled
        currency
        productsPerPage
        gridColumns
      }
      programs {
        __typename
        enabled
      }
      events {
        __typename
        enabled
      }
    }
  }
  siteName
  tagline
  logo {
    __typename
    main
    icon
    light
  }
  theme {
    __typename
    primaryColor
    secondaryColor
    accentColor
    backgroundColor
    textColor
  }
  fonts {
    __typename
    pairing
  }
  layout {
    __typename
    homepage
    navbar
    footer
  }
  social {
    __typename
    facebook
    instagram
    twitter
    linkedin
    youtube
    tiktok
  }
  contact {
    __typename
    email
    phone
    address
  }
  analytics {
    __typename
    googleAnalyticsId
    facebookPixelId
    plausibleDomain
  }
  seo {
    __typename
    titleTemplate
    defaultDescription
    defaultOgImage
  }
}

fragment PagesParts on Pages {
  __typename
  title
  description
  ogImage
  blocks {
    __typename
    ... on PagesBlocksTextBlock {
      heading
      content
      alignment
    }
    ... on PagesBlocksHeroBanner {
      title
      subtitle
      backgroundImage
      buttonText
      buttonLink
      height
    }
    ... on PagesBlocksImageTextLeft {
      image
      imageAlt
      heading
      content
      buttonText
      buttonLink
    }
    ... on PagesBlocksImageTextRight {
      image
      imageAlt
      heading
      content
      buttonText
      buttonLink
    }
    ... on PagesBlocksCardsGrid {
      heading
      subheading
      columns
      cards {
        __typename
        title
        description
        image
        icon
        link
      }
    }
    ... on PagesBlocksCtaBox {
      heading
      text
      buttonText
      buttonLink
      backgroundImage
      style
    }
    ... on PagesBlocksFaq {
      heading
      items {
        __typename
        question
        answer
      }
    }
    ... on PagesBlocksImageGallery {
      heading
      layout
      images {
        __typename
        src
        alt
        caption
      }
    }
    ... on PagesBlocksContactInfo {
      heading
      showForm
      showMap
      mapEmbedUrl
    }
    ... on PagesBlocksStats {
      heading
      stats {
        __typename
        number
        label
        icon
      }
    }
    ... on PagesBlocksTestimonials {
      heading
      layout
      items {
        __typename
        quote
        author
        role
        avatar
      }
    }
    ... on PagesBlocksVideo {
      heading
      videoUrl
      thumbnail
      caption
    }
    ... on PagesBlocksTimeline {
      heading
      items {
        __typename
        year
        title
        description
        image
      }
    }
    ... on PagesBlocksTeam {
      heading
      subheading
      members {
        __typename
        name
        role
        photo
        bio
        linkedin
        twitter
        email
      }
    }
    ... on PagesBlocksDivider {
      style
      size
    }
    ... on PagesBlocksProductGrid {
      heading
      subheading
      displayMode
      category
      maxProducts
      columns
    }
    ... on PagesBlocksProductShowcase {
      heading
      productSlug
      layout
      backgroundColor
    }
  }
}

fragment HomeParts on Home {
  __typename
  title
  description
  hero {
    __typename
    slides {
      __typename
      title
      subtitle
      backgroundImage
      buttonText
      buttonLink
    }
  }
  blocks {
    __typename
    ... on HomeBlocksTextBlock {
      heading
      content
      alignment
    }
    ... on HomeBlocksHeroBanner {
      title
      subtitle
      backgroundImage
      buttonText
      buttonLink
      height
    }
    ... on HomeBlocksImageTextLeft {
      image
      imageAlt
      heading
      content
      buttonText
      buttonLink
    }
    ... on HomeBlocksImageTextRight {
      image
      imageAlt
      heading
      content
      buttonText
      buttonLink
    }
    ... on HomeBlocksCardsGrid {
      heading
      subheading
      columns
      cards {
        __typename
        title
        description
        image
        icon
        link
      }
    }
    ... on HomeBlocksCtaBox {
      heading
      text
      buttonText
      buttonLink
      backgroundImage
      style
    }
    ... on HomeBlocksFaq {
      heading
      items {
        __typename
        question
        answer
      }
    }
    ... on HomeBlocksImageGallery {
      heading
      layout
      images {
        __typename
        src
        alt
        caption
      }
    }
    ... on HomeBlocksContactInfo {
      heading
      showForm
      showMap
      mapEmbedUrl
    }
    ... on HomeBlocksStats {
      heading
      stats {
        __typename
        number
        label
        icon
      }
    }
    ... on HomeBlocksTestimonials {
      heading
      layout
      items {
        __typename
        quote
        author
        role
        avatar
      }
    }
    ... on HomeBlocksVideo {
      heading
      videoUrl
      thumbnail
      caption
    }
    ... on HomeBlocksTimeline {
      heading
      items {
        __typename
        year
        title
        description
        image
      }
    }
    ... on HomeBlocksTeam {
      heading
      subheading
      members {
        __typename
        name
        role
        photo
        bio
        linkedin
        twitter
        email
      }
    }
    ... on HomeBlocksDivider {
      style
      size
    }
    ... on HomeBlocksProductGrid {
      heading
      subheading
      displayMode
      category
      maxProducts
      columns
    }
    ... on HomeBlocksProductShowcase {
      heading
      productSlug
      layout
      backgroundColor
    }
  }
}

fragment ProductsParts on Products {
  __typename
  name
  slug
  description
  longDescription
  productType
  pricing {
    __typename
    price
    compareAtPrice
    taxable
  }
  images {
    __typename
    src
    alt
  }
  category
  tags
  inventory {
    __typename
    trackInventory
    quantity
    sku
    allowBackorder
  }
  physical {
    __typename
    weight
    length
    width
    height
    requiresShipping
  }
  digital {
    __typename
    downloadUrl
    fileType
    fileSize
    downloadLimit
  }
  service {
    __typename
    duration
    requiresBooking
    bookingUrl
  }
  variants {
    __typename
    name
    sku
    price
    quantity
    image
  }
  seo {
    __typename
    metaTitle
    metaDescription
    ogImage
  }
  status
  featured
}
